### ISSUE TITLE
A suggestion to avoid confusion

### ISSUE THREAD

**Issue by neodave** [tribalmedia/FMPhotoPicker#15]
Your use of the term ForceCrop was not what I expected. In my use case I am having a user pick a profile pic that will be circular, so I need to force them to edit their selected photo with a circle crop. It took me awhile to understand why turning on forceCrop didn't result in that behavior, but rather forces a single crop option. IMHO ForceCrop should be named CropChoice or CropDefault.

This is an amazing framework, thank you for open sourcing it.

**Comment by n-cong** [comment]
@neodave 
Sorry for the inconvenience and Thank you for your recommendation.
Yes. You are right. Since the term `ForceCrop` may cause some misunderstanding, we will consider to change it in a future release.

**Comment by wakaryry** [comment]
In my usage, I want to hide the crop tab and images show the cropped when I set `config.forceCropEnabled = true` and `config.availableCrops = [FMCrop.ratioSquare]`.

But now it seems I need to tap the crop button to make it cropped.

**Comment by n-cong** [comment]
@wakaryry 
Currently, we don't provide any way to hide tabs. But your PRs are always welcome :)

If you set `forceCropEnabled` to `true` then FMPhotoPicker will use the first crop option to crop images without requiring any additional action.
